/**
 * Canonical ingredient catalog for the trusted recipe domain (CLAUDE.md §15
 * Milestone 3, §9 "ingredients" / "ingredient_nutrients").
 *
 * `nutrients.provenance` is honest about how each figure was sourced:
 *
 * - `'usda_fdc'` — read from the USDA FoodData Central API (SR Legacy), with
 *   the `fdcId` it came from. These are the recipes' primary macro drivers
 *   (proteins, starches) — the numbers the portion engine scales.
 * - `'reference_estimate'` — well-established, nutrition-label-grade generic
 *   values for composite or minor ingredients (a dressing, a sautéed greens
 *   side) that don't map to one FDC entry. Flagged for backfill once this
 *   catalog grows past its starter batch — see the README milestone note.
 *
 * All basis figures are per 100 g unless noted. Density facts (`gramsPerCup`
 * etc.) let recipes write quantities the way a person would ("1½ cups rice")
 * while the nutrition engine still works in grams.
 */

import type { Ingredient } from './types';

export const INGREDIENTS: Ingredient[] = [
  {
    id: 'chicken-breast',
    canonicalName: 'Chicken breast, skinless, roasted',
    defaultUnit: 'g',
    allergens: [],
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 165,
      proteinG: 31.0,
      carbsG: 0,
      fatG: 3.57,
      fiberG: 0,
      provenance: 'usda_fdc',
      fdcId: '171477',
    },
  },
  {
    id: 'salmon-atlantic',
    canonicalName: 'Salmon, Atlantic, farmed, cooked',
    defaultUnit: 'g',
    allergens: ['fish'],
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 206,
      proteinG: 22.1,
      carbsG: 0,
      fatG: 12.4,
      fiberG: 0,
      provenance: 'usda_fdc',
      fdcId: '175168',
    },
  },
  {
    id: 'ground-turkey-93',
    canonicalName: 'Ground turkey, 93% lean, broiled',
    defaultUnit: 'g',
    allergens: [],
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 207,
      proteinG: 25.9,
      carbsG: 0,
      fatG: 11.4,
      fiberG: 0,
      provenance: 'usda_fdc',
      fdcId: '174492',
    },
  },
  {
    id: 'beef-flank-steak',
    canonicalName: 'Beef flank steak, trimmed, broiled',
    defaultUnit: 'g',
    allergens: [],
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 202,
      proteinG: 27.6,
      carbsG: 0,
      fatG: 9.31,
      fiberG: 0,
      provenance: 'usda_fdc',
      fdcId: '169435',
    },
  },
  {
    id: 'black-beans-canned',
    canonicalName: 'Black beans, canned, drained',
    defaultUnit: 'g',
    allergens: [],
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 91,
      proteinG: 6.03,
      carbsG: 16.6,
      fatG: 0.29,
      fiberG: 6.9,
      provenance: 'usda_fdc',
      fdcId: '175188',
    },
  },
  {
    id: 'white-rice-cooked',
    canonicalName: 'White rice, cooked',
    defaultUnit: 'g',
    allergens: [],
    gramsPerCup: 158,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 130,
      proteinG: 2.38,
      carbsG: 28.6,
      fatG: 0.21,
      fiberG: 0.4,
      provenance: 'usda_fdc',
      fdcId: '168880',
    },
  },
  {
    id: 'spinach-pasta-cooked',
    canonicalName: 'Pasta, cooked',
    defaultUnit: 'g',
    allergens: ['gluten'],
    gramsPerCup: 140,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 130,
      proteinG: 4.58,
      carbsG: 26.2,
      fatG: 0.63,
      fiberG: 2.4,
      provenance: 'usda_fdc',
      fdcId: '168912',
      note: 'FDC entry is spinach spaghetti; used as the closest verified proxy for cooked pasta. Fiber is a typical-pasta estimate, not from the fetched record.',
    },
  },
  {
    id: 'orzo-cooked',
    canonicalName: 'Orzo pasta, cooked',
    defaultUnit: 'g',
    allergens: ['gluten'],
    gramsPerCup: 150,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 128,
      proteinG: 4.53,
      carbsG: 26.6,
      fatG: 0.11,
      fiberG: 1.8,
      provenance: 'usda_fdc',
      fdcId: '168904',
      note: 'FDC entry is enriched vegetable macaroni, used as the closest verified proxy for orzo (same small-wheat-pasta profile). Fiber is a typical-pasta estimate.',
    },
  },
  {
    id: 'roasted-mixed-vegetables',
    canonicalName: 'Roasted mixed vegetables (zucchini, bell pepper, onion)',
    defaultUnit: 'g',
    allergens: [],
    gramsPerCup: 150,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 40,
      proteinG: 1.5,
      carbsG: 8,
      fatG: 0.5,
      fiberG: 2.5,
      provenance: 'reference_estimate',
      note: 'Composite of common roasting vegetables; pending FDC-backed per-vegetable breakdown.',
    },
  },
  {
    id: 'lemon-herb-dressing',
    canonicalName: 'Lemon herb dressing',
    defaultUnit: 'g',
    allergens: [],
    gramsPerTbsp: 14,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 470,
      proteinG: 0.5,
      carbsG: 2,
      fatG: 50,
      fiberG: 0,
      provenance: 'reference_estimate',
      note: 'Olive-oil-based vinaigrette (oil, lemon juice, herbs); pending a verified per-brand or from-scratch breakdown.',
    },
  },
  {
    id: 'sesame-sauteed-greens',
    canonicalName: 'Sesame sautéed greens',
    defaultUnit: 'g',
    allergens: [],
    gramsPerCup: 120,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 90,
      proteinG: 3,
      carbsG: 4,
      fatG: 7,
      fiberG: 2,
      provenance: 'reference_estimate',
      note: 'Bok choy/spinach sautéed in a little sesame oil; composite estimate pending per-ingredient breakdown.',
    },
  },
  {
    id: 'miso-ginger-glaze',
    canonicalName: 'Miso ginger glaze',
    defaultUnit: 'g',
    allergens: ['soy'],
    gramsPerTbsp: 17,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 150,
      proteinG: 6,
      carbsG: 18,
      fatG: 6,
      fiberG: 1,
      provenance: 'reference_estimate',
      note: 'Miso paste, ginger, garlic, a little oil; composite estimate pending per-ingredient breakdown.',
    },
  },
  {
    id: 'cherry-tomatoes',
    canonicalName: 'Cherry tomatoes, raw',
    defaultUnit: 'g',
    allergens: [],
    gramsPerCup: 150,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 18,
      proteinG: 0.9,
      carbsG: 3.9,
      fatG: 0.2,
      fiberG: 1.2,
      provenance: 'reference_estimate',
    },
  },
  {
    id: 'basil-pesto',
    canonicalName: 'Basil pesto',
    defaultUnit: 'g',
    allergens: ['tree-nut', 'dairy'],
    gramsPerTbsp: 14,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 303,
      proteinG: 4,
      carbsG: 5,
      fatG: 30,
      fiberG: 1,
      provenance: 'reference_estimate',
      note: 'Basil, pine nuts, parmesan, olive oil; jarred/from-scratch pesto composite.',
    },
  },
  {
    id: 'parmesan-grated',
    canonicalName: 'Parmesan cheese, grated',
    defaultUnit: 'g',
    allergens: ['dairy'],
    gramsPerTbsp: 5,
    gramsPerCup: 100,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 420,
      proteinG: 38,
      carbsG: 3.2,
      fatG: 28,
      fiberG: 0,
      provenance: 'reference_estimate',
    },
  },
  {
    id: 'corn-tortilla',
    canonicalName: 'Corn tortilla',
    defaultUnit: 'piece',
    allergens: [],
    gramsPerPiece: 26,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 218,
      proteinG: 5.7,
      carbsG: 44,
      fatG: 2.9,
      fiberG: 4.9,
      provenance: 'reference_estimate',
    },
  },
  {
    id: 'flour-tortilla',
    canonicalName: 'Flour tortilla',
    defaultUnit: 'piece',
    allergens: ['gluten'],
    gramsPerPiece: 45,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 310,
      proteinG: 8,
      carbsG: 50,
      fatG: 7,
      fiberG: 3,
      provenance: 'reference_estimate',
    },
  },
  {
    id: 'roasted-sweet-potato-pepper',
    canonicalName: 'Roasted sweet potato and bell pepper',
    defaultUnit: 'g',
    allergens: [],
    gramsPerCup: 150,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 85,
      proteinG: 1.5,
      carbsG: 19,
      fatG: 0.3,
      fiberG: 2.8,
      provenance: 'reference_estimate',
    },
  },
  {
    id: 'avocado',
    canonicalName: 'Avocado, raw',
    defaultUnit: 'piece',
    allergens: [],
    gramsPerPiece: 150,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 160,
      proteinG: 2,
      carbsG: 8.5,
      fatG: 14.7,
      fiberG: 6.7,
      provenance: 'reference_estimate',
    },
  },
  {
    id: 'butter-lettuce',
    canonicalName: 'Butter lettuce leaves, raw',
    defaultUnit: 'piece',
    allergens: [],
    gramsPerPiece: 10,
    gramsPerCup: 55,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 13,
      proteinG: 1.3,
      carbsG: 2.2,
      fatG: 0.2,
      fiberG: 1,
      provenance: 'reference_estimate',
    },
  },
  {
    id: 'pickled-carrots',
    canonicalName: 'Quick-pickled carrots',
    defaultUnit: 'g',
    allergens: [],
    gramsPerCup: 110,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 41,
      proteinG: 0.9,
      carbsG: 9.6,
      fatG: 0.2,
      fiberG: 2.8,
      provenance: 'reference_estimate',
    },
  },
  {
    id: 'ginger-soy-glaze',
    canonicalName: 'Ginger soy glaze',
    defaultUnit: 'g',
    allergens: ['soy', 'gluten'],
    gramsPerTbsp: 16,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 120,
      proteinG: 4,
      carbsG: 12,
      fatG: 6,
      fiberG: 0.5,
      provenance: 'reference_estimate',
      note: 'Soy sauce, ginger, garlic, a little oil; composite estimate pending per-ingredient breakdown.',
    },
  },
  {
    id: 'crushed-tomatoes',
    canonicalName: 'Crushed tomatoes, canned',
    defaultUnit: 'g',
    allergens: [],
    gramsPerCup: 245,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 32,
      proteinG: 1.6,
      carbsG: 7.1,
      fatG: 0.3,
      fiberG: 1.5,
      provenance: 'reference_estimate',
    },
  },
  {
    id: 'baby-spinach',
    canonicalName: 'Baby spinach, raw',
    defaultUnit: 'g',
    allergens: [],
    gramsPerCup: 30,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 23,
      proteinG: 2.9,
      carbsG: 3.6,
      fatG: 0.4,
      fiberG: 2.2,
      provenance: 'reference_estimate',
    },
  },
  {
    id: 'heavy-cream',
    canonicalName: 'Heavy cream',
    defaultUnit: 'g',
    allergens: ['dairy'],
    gramsPerTbsp: 15,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 340,
      proteinG: 2.1,
      carbsG: 2.8,
      fatG: 36,
      fiberG: 0,
      provenance: 'reference_estimate',
    },
  },
  {
    id: 'roasted-peppers-onions',
    canonicalName: 'Roasted bell peppers and onions',
    defaultUnit: 'g',
    allergens: [],
    gramsPerCup: 130,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 35,
      proteinG: 1,
      carbsG: 8,
      fatG: 0.2,
      fiberG: 2,
      provenance: 'reference_estimate',
    },
  },
  {
    id: 'olive-oil',
    canonicalName: 'Olive oil',
    defaultUnit: 'g',
    allergens: [],
    gramsPerTbsp: 13.5,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 884,
      proteinG: 0,
      carbsG: 0,
      fatG: 100,
      fiberG: 0,
      provenance: 'reference_estimate',
    },
  },
];

export const INGREDIENT_LOOKUP: Record<string, Ingredient> = Object.fromEntries(
  INGREDIENTS.map((ingredient) => [ingredient.id, ingredient]),
);

export function getIngredient(id: string): Ingredient {
  const ingredient = INGREDIENT_LOOKUP[id];
  if (!ingredient) throw new Error(`Unknown ingredient id "${id}".`);
  return ingredient;
}
