/**
 * Canonical ingredient catalog for the trusted recipe domain (CLAUDE.md §15
 * Milestone 3, §9 "ingredients" / "ingredient_nutrients").
 *
 * `nutrients.provenance` is honest about how each figure was sourced:
 *
 * - `'usda_fdc'` — read from the USDA FoodData Central API (SR Legacy), with
 *   the `fdcId` it came from. This is most of the catalog: every single-food
 *   ingredient (proteins, starches, produce) is FDC-verified.
 * - `'reference_estimate'` — well-established, nutrition-label-grade generic
 *   values for genuinely composite preparations (a dressing, a glaze) that
 *   don't map to one FDC entry — a sauce blended from several ingredients,
 *   not a single food. Flagged for backfill with a from-scratch or per-brand
 *   breakdown as the catalog matures.
 *
 * All basis figures are per 100 g unless noted. Density facts (`gramsPerCup`
 * etc.) let recipes write quantities the way a person would ("1½ cups rice")
 * while the nutrition engine still works in grams.
 */

import type { Ingredient } from './types';

export const INGREDIENTS: Ingredient[] = [
  {
    id: 'chicken-breast',
    canonicalName: 'Chicken breast, skinless, roasted',
    defaultUnit: 'g',
    allergens: [],
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 165,
      proteinG: 31.0,
      carbsG: 0,
      fatG: 3.57,
      fiberG: 0,
      provenance: 'usda_fdc',
      fdcId: '171477',
    },
  },
  {
    id: 'salmon-atlantic',
    canonicalName: 'Salmon, Atlantic, farmed, cooked',
    defaultUnit: 'g',
    allergens: ['fish'],
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 206,
      proteinG: 22.1,
      carbsG: 0,
      fatG: 12.4,
      fiberG: 0,
      provenance: 'usda_fdc',
      fdcId: '175168',
    },
  },
  {
    id: 'ground-turkey-93',
    canonicalName: 'Ground turkey, 93% lean, broiled',
    defaultUnit: 'g',
    allergens: [],
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 207,
      proteinG: 25.9,
      carbsG: 0,
      fatG: 11.4,
      fiberG: 0,
      provenance: 'usda_fdc',
      fdcId: '174492',
    },
  },
  {
    id: 'beef-flank-steak',
    canonicalName: 'Beef flank steak, trimmed, broiled',
    defaultUnit: 'g',
    allergens: [],
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 202,
      proteinG: 27.6,
      carbsG: 0,
      fatG: 9.31,
      fiberG: 0,
      provenance: 'usda_fdc',
      fdcId: '169435',
    },
  },
  {
    id: 'black-beans-canned',
    canonicalName: 'Black beans, canned, drained',
    defaultUnit: 'g',
    allergens: [],
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 91,
      proteinG: 6.03,
      carbsG: 16.6,
      fatG: 0.29,
      fiberG: 6.9,
      provenance: 'usda_fdc',
      fdcId: '175188',
    },
  },
  {
    id: 'shrimp-cooked',
    canonicalName: 'Shrimp, cooked',
    defaultUnit: 'g',
    allergens: ['shellfish'],
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 119,
      proteinG: 22.8,
      carbsG: 1.52,
      fatG: 1.7,
      fiberG: 0,
      provenance: 'usda_fdc',
      fdcId: '171971',
    },
  },
  {
    id: 'pork-tenderloin-cooked',
    canonicalName: 'Pork tenderloin, lean, roasted',
    defaultUnit: 'g',
    allergens: [],
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 143,
      proteinG: 26.2,
      carbsG: 0,
      fatG: 3.51,
      fiberG: 0,
      provenance: 'usda_fdc',
      fdcId: '168250',
    },
  },
  {
    id: 'tofu-firm',
    canonicalName: 'Tofu, firm',
    defaultUnit: 'g',
    allergens: ['soy'],
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 144,
      proteinG: 17.3,
      carbsG: 2.78,
      fatG: 8.72,
      fiberG: 0.3,
      provenance: 'usda_fdc',
      fdcId: '172475',
    },
  },
  {
    id: 'white-rice-cooked',
    canonicalName: 'White rice, cooked',
    defaultUnit: 'g',
    allergens: [],
    gramsPerCup: 158,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 130,
      proteinG: 2.38,
      carbsG: 28.6,
      fatG: 0.21,
      fiberG: 0.4,
      provenance: 'usda_fdc',
      fdcId: '168880',
    },
  },
  {
    id: 'spinach-pasta-cooked',
    canonicalName: 'Pasta, cooked',
    defaultUnit: 'g',
    allergens: ['gluten'],
    gramsPerCup: 140,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 130,
      proteinG: 4.58,
      carbsG: 26.2,
      fatG: 0.63,
      fiberG: 2.4,
      provenance: 'usda_fdc',
      fdcId: '168912',
      note: 'FDC entry is spinach spaghetti; used as the closest verified proxy for cooked pasta. Fiber is a typical-pasta estimate, not from the fetched record.',
    },
  },
  {
    id: 'orzo-cooked',
    canonicalName: 'Orzo pasta, cooked',
    defaultUnit: 'g',
    allergens: ['gluten'],
    gramsPerCup: 150,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 128,
      proteinG: 4.53,
      carbsG: 26.6,
      fatG: 0.11,
      fiberG: 1.8,
      provenance: 'usda_fdc',
      fdcId: '168904',
      note: 'FDC entry is enriched vegetable macaroni, used as the closest verified proxy for orzo (same small-wheat-pasta profile). Fiber is a typical-pasta estimate.',
    },
  },
  {
    id: 'quinoa-cooked',
    canonicalName: 'Quinoa, cooked',
    defaultUnit: 'g',
    allergens: [],
    gramsPerCup: 185,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 120,
      proteinG: 4.4,
      carbsG: 21.3,
      fatG: 1.92,
      fiberG: 2.8,
      provenance: 'usda_fdc',
      fdcId: '168917',
    },
  },
  {
    id: 'couscous-cooked',
    canonicalName: 'Couscous, cooked',
    defaultUnit: 'g',
    allergens: ['gluten'],
    gramsPerCup: 175,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 112,
      proteinG: 3.79,
      carbsG: 23.2,
      fatG: 0.16,
      fiberG: 1.4,
      provenance: 'usda_fdc',
      fdcId: '169700',
    },
  },
  {
    id: 'sweet-potato-cooked',
    canonicalName: 'Sweet potato, cooked',
    defaultUnit: 'g',
    allergens: [],
    gramsPerCup: 200,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 90,
      proteinG: 2.01,
      carbsG: 20.7,
      fatG: 0.15,
      fiberG: 3.3,
      provenance: 'usda_fdc',
      fdcId: '170134',
    },
  },
  {
    id: 'bell-pepper-red',
    canonicalName: 'Bell pepper, red, raw',
    defaultUnit: 'g',
    allergens: [],
    gramsPerCup: 150,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 26,
      proteinG: 0.99,
      carbsG: 6.03,
      fatG: 0.3,
      fiberG: 2.1,
      provenance: 'usda_fdc',
      fdcId: '170108',
    },
  },
  {
    id: 'onion',
    canonicalName: 'Onion, raw',
    defaultUnit: 'g',
    allergens: [],
    gramsPerCup: 160,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 40,
      proteinG: 1.1,
      carbsG: 9.34,
      fatG: 0.1,
      fiberG: 1.7,
      provenance: 'usda_fdc',
      fdcId: '170000',
    },
  },
  {
    id: 'zucchini',
    canonicalName: 'Zucchini, raw',
    defaultUnit: 'g',
    allergens: [],
    gramsPerCup: 124,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 17,
      proteinG: 1.21,
      carbsG: 3.11,
      fatG: 0.32,
      fiberG: 1.0,
      provenance: 'usda_fdc',
      fdcId: '169291',
    },
  },
  {
    id: 'broccoli-cooked',
    canonicalName: 'Broccoli, cooked',
    defaultUnit: 'g',
    allergens: [],
    gramsPerCup: 156,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 35,
      proteinG: 2.38,
      carbsG: 7.18,
      fatG: 0.41,
      fiberG: 3.3,
      provenance: 'usda_fdc',
      fdcId: '168510',
    },
  },
  {
    id: 'cucumber',
    canonicalName: 'Cucumber, raw',
    defaultUnit: 'g',
    allergens: [],
    gramsPerCup: 119,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 10,
      proteinG: 0.59,
      carbsG: 2.16,
      fatG: 0.16,
      fiberG: 0.7,
      provenance: 'usda_fdc',
      fdcId: '169225',
    },
  },
  {
    id: 'mushrooms-white',
    canonicalName: 'Mushrooms, white, raw',
    defaultUnit: 'g',
    allergens: [],
    gramsPerCup: 70,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 22,
      proteinG: 3.09,
      carbsG: 3.26,
      fatG: 0.34,
      fiberG: 1.0,
      provenance: 'usda_fdc',
      fdcId: '169251',
    },
  },
  {
    id: 'cherry-tomatoes',
    canonicalName: 'Cherry tomatoes, raw',
    defaultUnit: 'g',
    allergens: [],
    gramsPerCup: 150,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 18,
      proteinG: 0.88,
      carbsG: 3.89,
      fatG: 0.2,
      fiberG: 1.2,
      provenance: 'usda_fdc',
      fdcId: '170457',
      note: 'FDC entry is the generic raw tomato record, used as the verified proxy for cherry tomatoes (near-identical macros).',
    },
  },
  {
    id: 'crushed-tomatoes',
    canonicalName: 'Crushed tomatoes, canned',
    defaultUnit: 'g',
    allergens: [],
    gramsPerCup: 245,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 32,
      proteinG: 1.64,
      carbsG: 7.29,
      fatG: 0.28,
      fiberG: 1.9,
      provenance: 'usda_fdc',
      fdcId: '170501',
    },
  },
  {
    id: 'baby-spinach',
    canonicalName: 'Baby spinach, raw',
    defaultUnit: 'g',
    allergens: [],
    gramsPerCup: 30,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 23,
      proteinG: 2.86,
      carbsG: 3.63,
      fatG: 0.39,
      fiberG: 2.2,
      provenance: 'usda_fdc',
      fdcId: '168462',
      note: 'FDC entry is generic raw spinach, used as the verified proxy for baby spinach.',
    },
  },
  {
    id: 'butter-lettuce',
    canonicalName: 'Butter lettuce leaves, raw',
    defaultUnit: 'piece',
    allergens: [],
    gramsPerPiece: 10,
    gramsPerCup: 55,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 13,
      proteinG: 1.35,
      carbsG: 2.23,
      fatG: 0.22,
      fiberG: 1.1,
      provenance: 'usda_fdc',
      fdcId: '168429',
    },
  },
  {
    id: 'pickled-carrots',
    canonicalName: 'Quick-pickled carrots',
    defaultUnit: 'g',
    allergens: [],
    gramsPerCup: 110,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 41,
      proteinG: 0.93,
      carbsG: 9.58,
      fatG: 0.24,
      fiberG: 2.8,
      provenance: 'usda_fdc',
      fdcId: '170393',
      note: 'Nutrient basis is raw carrots (FDC-verified) — a quick pickle drains most of its brine, so added sugar/salt per serving is negligible.',
    },
  },
  {
    id: 'avocado',
    canonicalName: 'Avocado, raw',
    defaultUnit: 'piece',
    allergens: [],
    gramsPerPiece: 150,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 167,
      proteinG: 1.96,
      carbsG: 8.64,
      fatG: 15.4,
      fiberG: 6.8,
      provenance: 'usda_fdc',
      fdcId: '171706',
    },
  },
  {
    id: 'corn-tortilla',
    canonicalName: 'Corn tortilla',
    defaultUnit: 'piece',
    allergens: [],
    gramsPerPiece: 26,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 218,
      proteinG: 5.7,
      carbsG: 44.6,
      fatG: 2.85,
      fiberG: 6.3,
      provenance: 'usda_fdc',
      fdcId: '175036',
    },
  },
  {
    id: 'flour-tortilla',
    canonicalName: 'Flour tortilla',
    defaultUnit: 'piece',
    allergens: ['gluten'],
    gramsPerPiece: 45,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 306,
      proteinG: 8.2,
      carbsG: 49.4,
      fatG: 7.99,
      fiberG: 3.5,
      provenance: 'usda_fdc',
      fdcId: '175037',
    },
  },
  {
    id: 'parmesan-grated',
    canonicalName: 'Parmesan cheese, grated',
    defaultUnit: 'g',
    allergens: ['dairy'],
    gramsPerTbsp: 5,
    gramsPerCup: 100,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 420,
      proteinG: 28.42,
      carbsG: 13.91,
      fatG: 27.84,
      fiberG: 0,
      provenance: 'usda_fdc',
      fdcId: '171247',
      note: 'This FDC entry is a shelf-stable canister-style grated parmesan (with anti-caking starch), hence the higher carbs than a fresh-grated wedge.',
    },
  },
  {
    id: 'heavy-cream',
    canonicalName: 'Heavy cream',
    defaultUnit: 'g',
    allergens: ['dairy'],
    gramsPerTbsp: 15,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 340,
      proteinG: 2.84,
      carbsG: 2.84,
      fatG: 36.1,
      fiberG: 0,
      provenance: 'usda_fdc',
      fdcId: '170859',
    },
  },
  {
    id: 'olive-oil',
    canonicalName: 'Olive oil',
    defaultUnit: 'g',
    allergens: [],
    gramsPerTbsp: 13.5,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 884,
      proteinG: 0,
      carbsG: 0,
      fatG: 100,
      fiberG: 0,
      provenance: 'usda_fdc',
      fdcId: '171413',
    },
  },

  // --- Composite preparations (sauces, dressings, glazes) ---------------
  // Genuinely multi-ingredient; no single FDC entry represents "a dressing"
  // or "a glaze". Left as reference_estimate until each is broken into its
  // own verified components.
  {
    id: 'lemon-herb-dressing',
    canonicalName: 'Lemon herb dressing',
    defaultUnit: 'g',
    allergens: [],
    gramsPerTbsp: 14,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 470,
      proteinG: 0.5,
      carbsG: 2,
      fatG: 50,
      fiberG: 0,
      provenance: 'reference_estimate',
      note: 'Olive-oil-based vinaigrette (oil, lemon juice, herbs); pending a verified per-brand or from-scratch breakdown.',
    },
  },
  {
    id: 'sesame-sauteed-greens',
    canonicalName: 'Sesame sautéed greens',
    defaultUnit: 'g',
    allergens: [],
    gramsPerCup: 120,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 90,
      proteinG: 3,
      carbsG: 4,
      fatG: 7,
      fiberG: 2,
      provenance: 'reference_estimate',
      note: 'Bok choy/spinach sautéed in a little sesame oil; composite estimate pending per-ingredient breakdown.',
    },
  },
  {
    id: 'miso-ginger-glaze',
    canonicalName: 'Miso ginger glaze',
    defaultUnit: 'g',
    allergens: ['soy'],
    gramsPerTbsp: 17,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 150,
      proteinG: 6,
      carbsG: 18,
      fatG: 6,
      fiberG: 1,
      provenance: 'reference_estimate',
      note: 'Miso paste, ginger, garlic, a little oil; composite estimate pending per-ingredient breakdown.',
    },
  },
  {
    id: 'basil-pesto',
    canonicalName: 'Basil pesto',
    defaultUnit: 'g',
    allergens: ['tree-nut', 'dairy'],
    gramsPerTbsp: 14,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 303,
      proteinG: 4,
      carbsG: 5,
      fatG: 30,
      fiberG: 1,
      provenance: 'reference_estimate',
      note: 'Basil, pine nuts, parmesan, olive oil; jarred/from-scratch pesto composite.',
    },
  },
  {
    id: 'ginger-soy-glaze',
    canonicalName: 'Ginger soy glaze',
    defaultUnit: 'g',
    allergens: ['soy', 'gluten'],
    gramsPerTbsp: 16,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 120,
      proteinG: 4,
      carbsG: 12,
      fatG: 6,
      fiberG: 0.5,
      provenance: 'reference_estimate',
      note: 'Soy sauce, ginger, garlic, a little oil; composite estimate pending per-ingredient breakdown.',
    },
  },
  {
    id: 'tzatziki-yogurt-sauce',
    canonicalName: 'Tzatziki yogurt sauce',
    defaultUnit: 'g',
    allergens: ['dairy'],
    gramsPerTbsp: 16,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 65,
      proteinG: 3.5,
      carbsG: 4,
      fatG: 4,
      fiberG: 0.3,
      provenance: 'reference_estimate',
      note: 'Greek yogurt, cucumber, garlic, olive oil, lemon; composite estimate pending per-ingredient breakdown.',
    },
  },
  {
    id: 'dijon-honey-glaze',
    canonicalName: 'Dijon honey glaze',
    defaultUnit: 'g',
    allergens: [],
    gramsPerTbsp: 18,
    nutrients: {
      basisAmount: 100,
      basisUnit: 'g',
      calories: 230,
      proteinG: 1.5,
      carbsG: 42,
      fatG: 6,
      fiberG: 0.5,
      provenance: 'reference_estimate',
      note: 'Dijon mustard, honey, a little olive oil; composite estimate pending per-ingredient breakdown.',
    },
  },
];

export const INGREDIENT_LOOKUP: Record<string, Ingredient> = Object.fromEntries(
  INGREDIENTS.map((ingredient) => [ingredient.id, ingredient]),
);

export function getIngredient(id: string): Ingredient {
  const ingredient = INGREDIENT_LOOKUP[id];
  if (!ingredient) throw new Error(`Unknown ingredient id "${id}".`);
  return ingredient;
}
