/**
 * Generates the seed SQL for the recipe/nutrition tables (Milestone 3) from
 * the single source of truth in `domain/recipes/`, so the database never
 * drifts from the TypeScript catalog by hand transcription.
 *
 * Usage: `npx tsx scripts/generate-recipe-seed-sql.ts > /tmp/recipe-seed.sql`
 * then apply the printed SQL against the project (Supabase SQL editor, the
 * MCP connector's `execute_sql`, or `psql`). Re-run and re-apply whenever
 * `domain/recipes/ingredients.ts` or `domain/recipes/catalog.ts` changes —
 * every statement here is an upsert, so re-applying is safe.
 */

import { RECIPE_CATALOG } from '../domain/recipes/catalog';
import { INGREDIENTS } from '../domain/recipes/ingredients';

function sqlString(value: string | undefined | null): string {
  if (value === undefined || value === null) return 'null';
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlArray(values: string[]): string {
  if (values.length === 0) return "'{}'";
  return `array[${values.map(sqlString).join(', ')}]`;
}

function sqlNumber(value: number | undefined | null): string {
  return value === undefined || value === null ? 'null' : String(value);
}

const lines: string[] = [];

lines.push('-- Generated by scripts/generate-recipe-seed-sql.ts — do not hand-edit.');
lines.push('begin;');
lines.push('');

for (const ingredient of INGREDIENTS) {
  lines.push(
    `insert into public.ingredients (id, canonical_name, default_unit, allergens, grams_per_cup, grams_per_tbsp, grams_per_piece)
values (${sqlString(ingredient.id)}, ${sqlString(ingredient.canonicalName)}, ${sqlString(ingredient.defaultUnit)}, ${sqlArray(ingredient.allergens)}, ${sqlNumber(ingredient.gramsPerCup)}, ${sqlNumber(ingredient.gramsPerTbsp)}, ${sqlNumber(ingredient.gramsPerPiece)})
on conflict (id) do update set
  canonical_name = excluded.canonical_name,
  default_unit = excluded.default_unit,
  allergens = excluded.allergens,
  grams_per_cup = excluded.grams_per_cup,
  grams_per_tbsp = excluded.grams_per_tbsp,
  grams_per_piece = excluded.grams_per_piece;`,
  );

  const n = ingredient.nutrients;
  lines.push(
    `insert into public.ingredient_nutrients (ingredient_id, basis_amount, basis_unit, calories, protein_g, carbs_g, fat_g, fiber_g, provenance, fdc_id, note)
values (${sqlString(ingredient.id)}, ${sqlNumber(n.basisAmount)}, ${sqlString(n.basisUnit)}, ${sqlNumber(n.calories)}, ${sqlNumber(n.proteinG)}, ${sqlNumber(n.carbsG)}, ${sqlNumber(n.fatG)}, ${sqlNumber(n.fiberG)}, ${sqlString(n.provenance)}, ${sqlString(n.fdcId)}, ${sqlString(n.note)})
on conflict (ingredient_id) do update set
  basis_amount = excluded.basis_amount,
  basis_unit = excluded.basis_unit,
  calories = excluded.calories,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  provenance = excluded.provenance,
  fdc_id = excluded.fdc_id,
  note = excluded.note;`,
  );
  lines.push('');
}

for (const recipe of RECIPE_CATALOG) {
  lines.push(
    `insert into public.recipes (id, slug, name, description, prep_minutes, cook_minutes, servings, dietary_tags, allergen_tags, instructions, image_key, image_alt, cost_per_serving, status)
values (${sqlString(recipe.id)}, ${sqlString(recipe.slug)}, ${sqlString(recipe.name)}, ${sqlString(recipe.description)}, ${sqlNumber(recipe.prepMinutes)}, ${sqlNumber(recipe.cookMinutes)}, ${sqlNumber(recipe.servings)}, ${sqlArray(recipe.dietaryTags)}, ${sqlArray(recipe.allergenTags)}, ${sqlArray(recipe.instructions)}, ${sqlString(recipe.imageKey)}, ${sqlString(recipe.imageAlt)}, ${sqlNumber(recipe.costPerServing)}, ${sqlString(recipe.status)})
on conflict (id) do update set
  slug = excluded.slug,
  name = excluded.name,
  description = excluded.description,
  prep_minutes = excluded.prep_minutes,
  cook_minutes = excluded.cook_minutes,
  servings = excluded.servings,
  dietary_tags = excluded.dietary_tags,
  allergen_tags = excluded.allergen_tags,
  instructions = excluded.instructions,
  image_key = excluded.image_key,
  image_alt = excluded.image_alt,
  cost_per_serving = excluded.cost_per_serving,
  status = excluded.status;`,
  );

  lines.push(`delete from public.recipe_ingredients where recipe_id = ${sqlString(recipe.id)};`);
  recipe.ingredients.forEach((ri, index) => {
    lines.push(
      `insert into public.recipe_ingredients (recipe_id, ingredient_id, role, quantity_amount, quantity_unit, preparation_note, is_optional, sort_order)
values (${sqlString(recipe.id)}, ${sqlString(ri.ingredientId)}, ${sqlString(ri.role)}, ${sqlNumber(ri.quantity.amount)}, ${sqlString(ri.quantity.unit)}, ${sqlString(ri.preparationNote)}, ${ri.isOptional ? 'true' : 'false'}, ${index});`,
    );
  });
  lines.push('');
}

lines.push('commit;');

console.log(lines.join('\n'));
